version: 2.12.2
commit: 'chore(version): bump to v%.%.%'
files:
  README.md:
    - coveralls-gradle-plugin v%.%.%
    - id 'com.github.kt3k.coveralls' version '%.%.%'
  build.gradle: version '%.%.%'
  gradle.properties: VERSION_NAME=%.%.%
